# Description:
#  JsInterop helper classes

package(default_visibility = ["//visibility:public"])

# Googleowns the copyright
licenses(["unencumbered"])

java_library(
    name = "base",
    srcs = glob(["*.java"]),
)
